From SimpleC.EE Require Import functional_queue_strategy_goal functional_queue_strategy_proof.

Module functional_queue_Strategy_Correctness : functional_queue_Strategy_Correct.
  Include functional_queue_strategy_proof.
End functional_queue_Strategy_Correctness.
